### ISSUE TITLE
Where is r2rM_bnbMS_2capt.pth1.4.bin

### ISSUE THREAD

**Issue by jasonppy** [airbert-vln/airbert-recurrentvln#1]
Thanks for making the codebase available!
Training Rec VLN BERT requires loading r2rM_bnbMS_2capt.pth1.4.bin at snap/vln-bert, but in the download link I only see val-unseen-best, which I guess is trained model right?

**Comment by cshizhe** [comment]
Hi, you could find the pretrained AirBERT in the [model zoo](https://github.com/airbert-vln/model-zoos).

**Comment by jasonppy** [comment]
I couldn't find a file named `r2rM_bnbMS_2capt.pth1.4.bin` in the model zoo, can you point the link to me?

**Comment by cshizhe** [comment]
I think the first author might rename the model. You could use the airbert.bin. Refer to [this](https://github.com/pytorch/pytorch/issues/48915) to use the model in pytorch 1.4.

**Comment by jasonppy** [comment]
I see, thanks
