### ISSUE TITLE
Where is the bert_base_6_layer_6_connect.json file used to initialize BertConfig?

### ISSUE THREAD

**Issue by Jackie-Chou** [airbert-vln/airbert-recurrentvln#2]
Hi, I am trying to run the code in my experiments. However, the configuration file used to initialize the BertConfig seems missing, which is used in L56 of vlnbert/vlnbert_init.py. Hope you can share this file.

**Comment by cshizhe** [comment]
Hi, you could download the config file from this [link](https://github.com/arjunmajum/vln-bert/blob/4cc3539df036f47e1e9b02bd64ef3734ec389da6/scripts/download-auxiliary-data.py).

**Comment by Jackie-Chou** [comment]
Thanks so much!
